/**
 * @file    notification.h
 * @brief   In-memory desktop notification record.
 *
 * A Notification is the unit posted to NotificationService: an id, title,
 * message, source app id, and a millisecond timestamp. The model is
 * intentionally minimal (no priority / actions / persistence) for the
 * Phase F minimal closed loop; richer fields are deferred.
 *
 * @author  CFDesktop Team
 * @date    2026-07-10
 * @version 0.19.0
 * @since   0.19.0
 * @ingroup notification
 */

#pragma once

#include <QString>

namespace cf::desktop::desktop_component {

/**
 * @brief  A single desktop notification.
 *
 * Carries the data rendered by the banner and the notification center. The
 * id is unique within the running shell; the timestamp is msec since epoch.
 *
 * @ingroup notification
 */
struct Notification {
    /// @brief Unique id (generated by NotificationService when left empty).
    QString id;

    /// @brief One-line title shown in the banner / center.
    QString title;

    /// @brief Body text shown under the title.
    QString message;

    /// @brief Source application id (e.g. "org.cf.mail").
    QString app_id;

    /// @brief Creation time, msec since the Unix epoch.
    qint64 timestamp{0};
};

} // namespace cf::desktop::desktop_component
